<?php

namespace MainBundle\Entity\Repository;

/**
 * SupporterAimRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SupporterAimRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserAims(\MainBundle\Entity\User $user)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select(
            array(
                //'DISTINCT(sa.aim)'
                'sa'
            )
        )
        ->from('MainBundle:SupporterAim', 'sa')
        ->where('sa.user = :user')
        ->groupBy('sa.aim')
        ->setParameter(':user', $user);
        $query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
    }

    public function getUsersByAim(\MainBundle\Entity\Aim $aim)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select(
            array(
                //'DISTINCT(sa.user)'
                'sa'
            )
        )
        ->from('MainBundle:SupporterAim', 'sa')
        ->where('sa.aim = :aim')
        ->groupBy('sa.user')
        ->setParameter(':aim', $aim);
        $query = $qb->getQuery();
        $result = $query->getResult();

        return $result;
    }


}
