<?php

namespace MainBundle\Entity\Repository;

/**
 * UserNotificationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNotificationRepository extends \Doctrine\ORM\EntityRepository
{
    public function getUserNotifications(\MainBundle\Entity\User $user, $lastId = null, $limit = 5)
    {
        $em = $this->getEntityManager();
        $qb = $em->createQueryBuilder();

        $qb->select(
            array(
                'un.id AS id',
                'IDENTITY (p.user) as user_id',
                "CONCAT(u2.firstname, ' ', u2.lastname) as user_fullname",
                'u2.username',
                'p.id AS post_id',
                'p.title',
                'p.content',
                'un.createdOn as created_on',
                'v.visionTimer as vision_timer'
            )
        )
        ->from('MainBundle:UserNotification', 'un')
        ->leftJoin('MainBundle:Post', 'p', 'WITH', 'p.id = un.post')
        ->leftJoin('MainBundle:Vision', 'v', 'WITH', 'p.id = v.post')
        ->leftJoin('MainBundle:User', 'u1', 'WITH', 'un.user = u1.id')
        ->leftJoin('MainBundle:User', 'u2', 'WITH', 'p.user = u2.id');
        //->leftJoin('MainBundle:User', 'u2', 'WITH', 'v.visionPerson = u2.id')
        //->leftJoin('MainBundle:Aim', 'a', 'WITH', 'p.aim = a.id')

        $qb->where($qb->expr()->eq('u1.id', ':userId'));
        $qb->setParameter(':userId', $user);

        if ($lastId != null)
        {
            $qb->andWhere($qb->expr()->lt('un.id', ':lastId'));
            $qb->setParameter(':lastId', $lastId);
        }

        $qb->orderBy('un.id', 'DESC');
        $qb->setMaxResults($limit);
        $query = $qb->getQuery();
        $result = $query->getArrayResult();

        return $result;
    }
}
