Creative\MainBundle\Entity\Document:
    properties:
        name:
            - NotNull: ~

        type: 
            - Type:
                type: integer
                message: The value {{ value }} is not a valid {{ type }}.
